### ISSUE TITLE
Building the image locally doesn't produce the same container as pulling from dockerhub

### ISSUE THREAD

**Issue by ignatiusab** [danielguerra69/alpine-sshd#3]
I cloned the repo and successfully do a docker build.
When running the new image with the same command as in the readme,
```
docker run -p 4848:22 --name alpine-sshd -d myImageName
```
the container automatically stop.
It works fine if I use the image from dockerhub.

**Comment by danielguerra69** [comment]
Its work fine with me. What is the output from: docker logs alpine-sshd ?

**Comment by ignatiusab** [comment]
I should've inform you that I changed the `ENTRYPOINT` into 
```Dockerfile
ENTRYPOINT docker-entrypoint.sh
```
Since using `["docker-entrypoint.sh"]` will give me this error when running it.
```
docker: Error response from daemon:
OCI runtime create failed: container_linux.go:348: starting container process caused 
"exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.
```

the output of `docker logs alpine-sshd`:
```
/usr/sbin/sshd: line 1: docker-entrypoint.sh: Permission denied
```

**Comment by ignatiusab** [comment]
I modify the Dockerfile a lil bit just to fix the permission issue.
```Dockerfile
# add entrypoint script
ADD --chown=root:root docker-entrypoint.sh /usr/local/bin
RUN chmod 700 /usr/local/bin/docker-entrypoint.sh
```
now the output of `docker logs alpine-sshd` is
```
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:<FINGERPRINT> root@alpine-sshd
The key's randomart image is:
+---[RSA 2048]----+

<RANDOM ART IMAGE>

+----[SHA256]-----+
Generating public/private dsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_dsa_key.
Your public key has been saved in /etc/ssh/ssh_host_dsa_key.pub.
The key fingerprint is:
SHA256:<FINGERPRINT> root@alpine-sshd
The key's randomart image is:
+---[DSA 1024]----+

<RANDOM ART IMAGE>

+----[SHA256]-----+
```
The container still stops automatically.

**Comment by danielguerra69** [comment]
So your first problem was execute rights on the file. You can do the chmod a+rx also in you repo.
If you changed the docker-entrypoint and it doesnt work this is not the place to talk about it. This is your own project. And if you want me to think along at least show your current entrypoint because thats is the problem.

**Comment by ignatiusab** [comment]
I did not make any changes to `docker-entrypoint.sh`

Anyway,
It works now after adding `chmod a+rx`as per your suggestion.

This is my Dockerfile looks like:
```Dockerfile
FROM alpine:edge

# add openssh and clean
RUN apk add --update openssh \
&& rm  -rf /tmp/* /var/cache/apk/*

# add entrypoint script
ADD docker-entrypoint.sh /usr/local/bin
RUN chmod a+rx /usr/local/bin/docker-entrypoint.sh

#make sure we get fresh keys
RUN rm -rf /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_dsa_key

EXPOSE 22
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/usr/sbin/sshd","-D"]
```

Thanks for your help and swift replies!
