### ISSUE TITLE
Password flow fails to authenticate ssh connection

### ISSUE THREAD

**Issue by kingces95** [danielguerra69/alpine-sshd#4]
On my mac, I tried the following 

```
docker run -p 4848:22 --name alpine-sshd --hostname alpine-sshd -d danielguerra/alpine-sshd
docker exec -ti alpine-sshd passwd
ssh -p 4848 -i id_rsa root@localhost
```

I expected to open an ssh shell, but instead I got an error `root@localhost: Permission denied (publickey,password,keyboard-interactive).`.

**Comment by kingces95** [comment]
Resolved using https://askubuntu.com/questions/497895/permission-denied-for-rootlocalhost-for-ssh-connection

**Comment by danielguerra69** [comment]
Reads the Readme again, I think you mist this part .. --volumes-from ssh-container

**Comment by kingces95** [comment]
Oh, I thought that command was under the section for using certs to do the authentication. I executed the commands in the section for using a password to do the authentication, and, in the end, I was able to get it working without attaching the volume, but only by updating the sshd config file... I got to use sed for the first time, which was cool. :)

**Comment by danielguerra69** [comment]
Great ! Yes the password method doesn't need a volume.
